### ISSUE TITLE
Problem installing in kibana 4.4

### ISSUE THREAD

**Issue by pg2455** [chenryn/kbn_sankey_vis#12]
I have been cloning this plugin in `installedPlugins` folder as mentioned here: https://www.elastic.co/guide/en/kibana/4.4/kibana-plugins.html. 

Relaunching Kibana is giving me this error:

 ```
 log   [12:26:50.186] [fatal] TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugins._new$ (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/src/server/plugins/PluginCollection.js:57:32)
    at tryCatch (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/prateekgupta/Documents/kibana-4.4.2-darwin-x64/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

I don't know this error. Can someone help me understand what I need to do to make this work?

**Comment by JuanCarniglia** [comment]
Are you still on Kibana 4.4?

**Comment by pg2455** [comment]
yeah!

**Comment by nikitacr7** [comment]
+1

**Comment by JuanCarniglia** [comment]
Ok, you are all facing the same issue? If so I will try and get a 4.4 release running.

**Comment by nikitacr7** [comment]
@JuanCarniglia 

Any updates?
