### ISSUE TITLE
Not able to install in Kibana 5.6

### ISSUE THREAD

**Issue by vishnubraj** [chenryn/kbn_sankey_vis#19]
I am getting below erroe while starting kibana...

Can you please check..

FATAL Error: Couldn't find preset "es2015" relative to directory "/usr/share/kibana/plugins/kbn_sankey_vis"
    at /usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/usr/share/kibana/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/share/kibana/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:79:32
    at next (native)

**Comment by joriws** [comment]
I see the very same error. Is ES2015 javascript related error?

**Comment by ghost** [comment]
Same Kibana 5.6.10. Please any idea how fix it?
